anchor_version = "0.24.2"
solana_version = "1.9.13"


[provider]
cluster = "https://metaplex.devnet.rpcpool.com/"
wallet = "/Users/bhargavveepuri/wallets/solana/solana-wallet_linux/ryaNsMVq6FaS4oYT6gXxKsPEzGqryWmMb2PQKABsSRX.json"


[programs.devnet]
apl_stake_pool = "ASPXjbyfki5TsXHu4eBmsqqhKNJLhPqJ4wj7gsgW18F6"
apl_reward_distributor = "ARDCbrxKAMA2pCBAAa5TUSi5SYMvobfPnHB97mu44EMY"
apl_receipt_manager = "ARMm8GbQqVmq4jNw4tYZWSC2BMVdSD31PDVKd6tchJik"
apl_payment_manager = "APMT8qWbAUapzsBoxx1ACrt37JFWS76Bkn9PUre5ybyn"

